# Generated by Django 5.0.2 on 2025-09-05 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_minimum_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='BidValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(choices=[('VELOCITY', 'Bid Velocity Check'), ('AMOUNT', 'Bid Amount Validation'), ('PATTERN', 'Suspicious Pattern'), ('BEHAVIOR', 'User Behavior Analysis'), ('IP', 'IP Address Check'), ('DEVICE', 'Device Fingerprint')], max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('details', models.JSONField(default=dict, help_text='Additional validation details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='App.bidnow')),
            ],
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH_RISK_BID', 'High Risk Bid'), ('SUSPICIOUS_PATTERN', 'Suspicious Bidding Pattern'), ('VELOCITY_ABUSE', 'Bid Velocity Abuse'), ('AMOUNT_ANOMALY', 'Bid Amount Anomaly'), ('MULTIPLE_ACCOUNTS', 'Multiple Account Usage'), ('AUTO_BIDDING', 'Automated Bidding Detected')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('risk_score', models.FloatField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.bidnow')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0, help_text='Risk score from 0-100')),
                ('total_bids', models.PositiveIntegerField(default=0)),
                ('successful_bids', models.PositiveIntegerField(default=0)),
                ('average_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_bid_time', models.DateTimeField(blank=True, null=True)),
                ('suspicious_activity_count', models.PositiveIntegerField(default=0)),
                ('account_age_days', models.PositiveIntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
