# Generated by Django 5.0.2 on 2025-11-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='seller',
        ),
    ]
